participants:
    - name: "name1"
      email: "some_email1@example.com"
      organizer: True
    - name: "name2"
      email: "some_email2@example.com"
    - name: "name3"
      email: "some_email3@example.com"

email_template:
    # There should be three placeholders in the template: {giver}, {receiver}, and {organizers}
    # {giver} and {receiver} will be replaced by the names of the matched givers and receivers
    # {organizers} will be replaced by the name(s) of the participants where organizer=True
    # Note: If you want to write the organizers yourself, just remove the {organizers} placeholder
    subject: "Secret Santa!"
    body: |
        Hi {giver},

        The moment we've all been waiting for is here! 🎉 You’ve been chosen as the Secret Santa for:

        **{receiver}**  

        Please keep this information secret until the big reveal! 🤫

        Make sure to find a thoughtful gift that fits within our agreed budget.

        Regards,
        {organizers}
